# Generated by Django 3.2.5 on 2021-07-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=200, null=True)),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, choices=[('Action and Adventure', 'Action and Adventure'), ('Classics', 'Classics'), ('Fiction', 'Fiction'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Personal Development', 'Personal Development'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Mystery', 'Mystery')], max_length=50, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Hungarian', 'Hungarian'), ('Gujarati', 'Gujarati'), ('Marathi', 'Marathi'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('French', 'French'), ('French', 'French'), ('Swedish', 'Swedish'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], max_length=50, null=True)),
            ],
        ),
    ]
